### ISSUE TITLE
How can I run tests?

### ISSUE THREAD

**Issue by sandervanhooft** [mantrajs/kickstart-mantrajs-webpack#5]
I've tried `npm test`, but that doesn't not seem to be configured in `packages.json`.

**Comment by tomitrescak** [comment]
Thanks for your feedback! I will try to incorporate all this today. To be honest, I only tested Wallaby.js. My fault.

**Comment by sandervanhooft** [comment]
No problem, loving this "lightweight" kickstarter pack so far. Looking forward to your mods.

**Comment by tomitrescak** [comment]
@arunoda would you have time to looks at this issue? I have configured what I know in the package.json, but am receiving following error:

```
npm run test

> kickstart-mantrajs-webpack@1.0.0 test /Users/tomi/Documents/Programming/Github/kickstart-mantra-webpack
> npm run lint && npm run testonly


> kickstart-mantrajs-webpack@1.0.0 lint /Users/tomi/Documents/Programming/Github/kickstart-mantra-webpack
> eslint ./lib ./client ./server --ext .js --ext .jsx


> kickstart-mantrajs-webpack@1.0.0 testonly /Users/tomi/Documents/Programming/Github/kickstart-mantra-webpack
> mocha .scripts/mocha_boot.js client/**/tests/**/*.js --compilers js:babel-core/register

/Users/tomi/Documents/Programming/Github/kickstart-mantra-webpack/node_modules/mocha/lib/utils.js:628
        throw new Error("cannot resolve path (or pattern) '" + path + "'");
        ^

Error: cannot resolve path (or pattern) '.scripts/mocha_boot.js'
    at Object.lookupFiles (/Users/tomi/Documents/Programming/Github/kickstart-mantra-webpack/node_modules/mocha/lib/utils.js:628:15)
    at /Users/tomi/Documents/Programming/Github/kickstart-mantra-webpack/node_modules/mocha/bin/_mocha:326:30
    at Array.forEach (native)
    at Object.<anonymous> (/Users/tomi/Documents/Programming/Github/kickstart-mantra-webpack/node_modules/mocha/bin/_mocha:325:6)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:118:18)
    at node.js:952:3

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "testonly"
npm ERR! node v4.1.2
npm ERR! npm  v3.5.1
npm ERR! code ELIFECYCLE
npm ERR! kickstart-mantrajs-webpack@1.0.0 testonly: `mocha .scripts/mocha_boot.js client/**/tests/**/*.js --compilers js:babel-core/register`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kickstart-mantrajs-webpack@1.0.0 testonly script 'mocha .scripts/mocha_boot.js client/**/tests/**/*.js --compilers js:babel-core/register'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the kickstart-mantrajs-webpack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha .scripts/mocha_boot.js client/**/tests/**/*.js --compilers js:babel-core/register
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs kickstart-mantrajs-webpack
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls kickstart-mantrajs-webpack
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tomi/Documents/Programming/Github/kickstart-mantra-webpack/npm-debug.log

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test"
npm ERR! node v4.1.2
npm ERR! npm  v3.5.1
npm ERR! code ELIFECYCLE
npm ERR! kickstart-mantrajs-webpack@1.0.0 test: `npm run lint && npm run testonly`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kickstart-mantrajs-webpack@1.0.0 test script 'npm run lint && npm run testonly'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the kickstart-mantrajs-webpack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run lint && npm run testonly
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs kickstart-mantrajs-webpack
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls kickstart-mantrajs-webpack
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tomi/Documents/Programming/Github/kickstart-mantra-webpack/npm-debug.log

Programming/Github/kickstart-mantra-webpack  master ✗
```

I am not big in shell scripting and could use some help.

**Comment by sandervanhooft** [comment]
Not an expert on that either, but the output mentiones the .scripts/mocha_boot.js is missing.

[This may be an interesting example](https://github.com/mantrajs/meteor-mantra-kickstarter/blob/v0.2.1/.scripts/mocha_boot.js).

**Comment by tomitrescak** [comment]
Yup, I was missing a script. But now am getting a following error:

```
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at loader (/Users/tomi/Documents/Programming/Github/kickstart-mantra-webpack/node_modules/babel-register/lib/node.js:126:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/tomi/Documents/Programming/Github/kickstart-mantra-webpack/node_modules/babel-register/lib/node.js:136:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/tomi/Documents/Programming/Github/kickstart-mantra-webpack/node_modules/mocha/lib/mocha.js:219:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/tomi/Documents/Programming/Github/kickstart-mantra-webpack/node_modules/mocha/lib/mocha.js:216:14)
    at Mocha.run (/Users/tomi/Documents/Programming/Github/kickstart-mantra-webpack/node_modules/mocha/lib/mocha.js:468:10)
    at Object.<anonymous> (/Users/tomi/Documents/Programming/Github/kickstart-mantra-webpack/node_modules/mocha/bin/_mocha:403:18)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:118:18)
    at node.js:952:3

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "testonly"
npm ERR! node v4.1.2
npm ERR! npm  v3.5.1
npm ERR! code ELIFECYCLE
npm ERR! kickstart-mantrajs-webpack@1.0.0 testonly: `mocha .scripts/mocha_boot.js src/client/**/tests/**/*.js --compilers js:babel-core/register`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kickstart-mantrajs-webpack@1.0.0 testonly script 'mocha .scripts/mocha_boot.js src/client/**/tests/**/*.js --compilers js:babel-core/register'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the kickstart-mantrajs-webpack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha .scripts/mocha_boot.js src/client/**/tests/**/*.js --compilers js:babel-core/register
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs kickstart-mantrajs-webpack
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls kickstart-mantrajs-webpack
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tomi/Documents/Programming/Github/kickstart-mantra-webpack/npm-debug.log

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test"
npm ERR! node v4.1.2
npm ERR! npm  v3.5.1
npm ERR! code ELIFECYCLE
npm ERR! kickstart-mantrajs-webpack@1.0.0 test: `npm run lint && npm run testonly`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kickstart-mantrajs-webpack@1.0.0 test script 'npm run lint && npm run testonly'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the kickstart-mantrajs-webpack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run lint && npm run testonly
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs kickstart-mantrajs-webpack
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls kickstart-mantrajs-webpack
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tomi/Documents/Programming/Github/kickstart-mantra-webpack/npm-debug.log
```

Looks like babel does not work in the pipeline?

**Comment by sandervanhooft** [comment]
Perhaps. Could it be a version issue, a missing (babel) package or a load order? [meteor-mantra-kickstarter/packages.json](https://github.com/mantrajs/meteor-mantra-kickstarter/blob/v0.2.1/package.json) vs [this/packages.json](https://github.com/mantrajs/kickstart-mantrajs-webpack/blob/master/package.json) ? I am not really familiar with the babel packages family.

**Comment by wiber** [comment]
What is the status of wallaby.js tests here?
